#include <rpc/rpc.h>
#include "avg.h"
#include <stdio.h>

/* run locally on 'server' called by a remote client. */
static double median;

/* 
 * routine notice the _1 the version number 
 * notice the client handle, not sued here but needs to be 
 * a parameter 
 */
double * average_1(input_data *input, CLIENT *client) 
  {

  /* input is paramters were marshalled by genrated routine */
  /*  a pointer to a double, is set to begining of data array  */
  double *dp = input->input_data.input_data_val;

  u_int i;
  median = 0;
  u_int j;
  u_int k;
  double sort;
  double middle1;
  double middle2;
  int size = input->input_data.input_data_len;
  int inputArr[size];

  /* iterate until end of number of times (data_len) */
  for ( i = 0; i < size; i++ ) {
    
    inputArr[i] = *dp;
    dp++;
   }

  /* Sort the input array */
  for ( j = 0; j < size; j++ ) {

     for (k = j + 1; k < size; k++ ) {

	if ( inputArr[j] > inputArr[k] ) {
      
           sort = inputArr[j];

           inputArr[j] = inputArr[k];

           inputArr[k] = sort; 

        }
     }
  }

  /* inputArr is now sorted from smallest to largest -> time to find median */
  
     //If the number of values inputted is EVEN
     if ( size % 2 == 0 ) {

         //get the actual middle value
         middle1 = inputArr[size / 2];

         //get the middle vlaue on the other side of the one above
         middle2 = inputArr[(size / 2) - 1];

         //find the median by adding them together and dividing it by 2
         median = (middle1 + middle2) / 2;
     }

     //If the number of values inputted is ODD
     else {
    
         median = inputArr[size / 2];
     }

  return( &median );
}

/* 
 * server stub 'average_1_svc function handle called in avg_svc that was
 * generated by rpcgen 
 * FYI:
 *   result = (*local)((char *)&argument, rqstp);
 *   where local is (char *(*)(char *, struct svc_req *)) average_1_svc;
 */
 
double * average_1_svc(input_data *input, struct svc_req *svc) 
  {
  CLIENT *client;
  return( average_1( input, client) );
  }
