#include "avg.h"
#include <stdio.h>

/*
 * routine notice the _1 the version number
 * notice the client handle, not sued here but needs to be
 * a parameter
 */
input_data * average_1(input_data *input, CLIENT *client) {
  //will hold the inputted string
  char *dp;

  /*  a pointer to a char *, is set to begining of data array  */
  dp = input->input_data.input_data_val;

      //set the data value to dp ~ input string
      input->input_data.input_data_val = dp;

  return( input );
}

/*
 * server stub 'average_1_svc function handle called in avg_svc that was
 * generated by rpcgen
 * FYI:
 *   result = (*local)((char *)&argument, rqstp);
 *   where local is (char *(*)(char *, struct svc_req *)) average_1_svc;
 */

input_data * average_1_svc(input_data *input, struct svc_req *svc)
  {
  CLIENT *client;
  return( average_1( input, client) );
  }


