//#include <rpc/rpc.h>
#include "avg.h"
#include <stdio.h>

/* run locally on 'server' called by a remote client. */
static double sum_avg;

/* 
 * routine notice the _1 the version number 
 * notice the client handle, not sued here but needs to be 
 * a parameter 
 */
input_data * average_1(input_data *input, CLIENT *client) {

  /* input is paramters were marshalled by genrated routine */
  /*  a pointer to a double, is set to begining of data array  */
  double *dp = input->input_data.input_data_val;

  int size = input->input_data.input_data_len;
  u_int i;
  sum_avg = 0;
  u_int j;
  u_int k;
  double sort;
  double ascendOrDescend;
  double ascend = 1.0;
  double descend = 2.0;

  /* Update input with dp */
  for( i = 0; i < size; i++ ) {
 
      input->input_data.input_data_val[i] = *dp;

      dp++;

     if ( i == size - 1) {
    
       ascendOrDescend = input->input_data.input_data_val[i];

       if (ascendOrDescend == ascend) {
 
            /* Sort the input array */
           for ( j = 0; j < size - 1; j++ ) {

              for (k = j + 1; k < size - 1; k++ ) {

                  if ( input->input_data.input_data_val[j] > input->input_data.input_data_val[k] ) {

                     sort = input->input_data.input_data_val[j];

                     input->input_data.input_data_val[j] = input->input_data.input_data_val[k];

                     input->input_data.input_data_val[k] = sort;
                  //end if 
	          }
              //end for k
              }
            //end for j     
            }
	//end if 
        }
         
 	else if (ascendOrDescend == descend) {
           /* Sort the input array */
           for ( j = 0; j < size - 1; j++ ) {

             for (k = j + 1; k < size - 1; k++ ) {

                if ( input->input_data.input_data_val[j] < input->input_data.input_data_val[k] ) {

                   sort = input->input_data.input_data_val[j];

		   input->input_data.input_data_val[j] = input->input_data.input_data_val[k];

                   input->input_data.input_data_val[k] = sort;
               	 
	          //end	if
                  }
       	      //end for	k
              }
       	    //end for j
            }

           //end else if
	   }
	 //end if
         }
    }

  return( input );
}

/* 
 * server stub 'average_1_svc function handle called in avg_svc that was
 * generated by rpcgen 
 * FYI:
 *   result = (*local)((char *)&argument, rqstp);
 *   where local is (char *(*)(char *, struct svc_req *)) average_1_svc;
 */
 
input_data * average_1_svc(input_data *input, struct svc_req *svc) 
  {
  CLIENT *client;
  return( average_1( input, client) );
  }
